---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes
      state: latest

  - name: install apache package
    yum:
      name: httpd
        
